-- Step 1: Enable vector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 2: Create movies table
CREATE TABLE IF NOT EXISTS movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  release_year INT2 NOT NULL, --  releaseYear in content.js
  content TEXT NOT NULL,
  embedding VECTOR(1024) -- vector dimension of liquid/lfm-2.5-embedding-350m:free is 1024
);

-- Step 3: Create Vector index (HNSW Index) to speed up similarity search
CREATE INDEX IF NOT EXISTS movies_embedding_hnsw_idx 
ON movies 
USING hnsw (embedding vector_cosine_ops);

-- Step 4: Create RPC function (match_movies)
CREATE OR REPLACE FUNCTION match_movies (
  query_embedding VECTOR(1024),
  match_threshold FLOAT DEFAULT 0.0,
  match_count INT DEFAULT 1
)
RETURNS TABLE (
  id BIGINT,
  title TEXT,
  release_year INT2,
  content TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    movies.id,
    movies.title,
    movies.release_year,
    movies.content,
    -- Calculate Cosine Similarity (1 - Cosine Distance)
    1 - (movies.embedding <=> query_embedding) AS similarity
  FROM movies
  WHERE 1 - (movies.embedding <=> query_embedding) > match_threshold
  ORDER BY movies.embedding <=> query_embedding ASC
  LIMIT match_count;
END;
$$;


-- For Gemini API (gemini-embedding-001 embedding model)
-- 1. Delete RPC function
drop function if exists match_movies;

-- 2. Clear old embeddings (Set embedding column to null)
update movies set embedding = null;

-- 3. Alter movies table (change embedding type to vector(768))
alter table movies 
alter column embedding type vector(768);

-- 4. Recreate RPC function
create or replace function match_movies (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  title text,
  content text,
  release_year int,
  similarity float
)
language sql stable
as $$
  select
    movies.id,
    movies.title,
    movies.content,
    movies.release_year,
    (1 - (movies.embedding <=> query_embedding))::float as similarity
  from movies
  where 1 - (movies.embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count;
$$;