-- Step 1: Enable vector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 2: Create movies table
CREATE TABLE IF NOT EXISTS movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  release_year INT2 NOT NULL, --  releaseYear in content.js
  content TEXT NOT NULL,
  embedding VECTOR(1024) -- vector dimension of liquid/lfm-2.5-embedding-350m:free is 1024
);

-- Step 3: Create Vector index (HNSW Index) to speed up similarity search
CREATE INDEX IF NOT EXISTS movies_embedding_hnsw_idx 
ON movies 
USING hnsw (embedding vector_cosine_ops);

-- Step 4: Create RPC function (match_movies)
CREATE OR REPLACE FUNCTION match_movies (
  query_embedding VECTOR(1536),
  match_threshold FLOAT DEFAULT 0.0,
  match_count INT DEFAULT 1
)
RETURNS TABLE (
  id BIGINT,
  title TEXT,
  release_year INT2,
  content TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    movies.id,
    movies.title,
    movies.release_year,
    movies.content,
    -- Calculate Cosine Similarity (1 - Cosine Distance)
    1 - (movies.embedding <=> query_embedding) AS similarity
  FROM movies
  WHERE 1 - (movies.embedding <=> query_embedding) > match_threshold
  ORDER BY movies.embedding <=> query_embedding ASC
  LIMIT match_count;
END;
$$;